import datetime

user_data_path = r'C:\Users\betan\Downloads\inserts_portfolio.sql'
output_path = r'C:\Users\betan\OneDrive\Desktop\Claude - JFB\Code\portfolio_analysis_complete.sql'

with open(user_data_path, 'r', encoding='utf-8') as f:
    user_inserts = f.read()

lines = []

lines.append("-- ============================================================")
lines.append("-- PORTFOLIO ANALYSIS - COMPLETE SQL SCRIPT")
lines.append("-- Generated: " + datetime.date.today().isoformat())
lines.append("-- Client: UHNW $95M Portfolio - Palo Alto")
lines.append("-- Assets: IXN (17.5%), QQQ (22.1%), IEF (28.5%), VNQ (8.9%), GLD (23.0%)")
lines.append("-- Data: 4,340 daily price records (868 per ticker, 2023-01-03 to 2026-06-18)")
lines.append("-- ============================================================")
lines.append("")

# ============ STEP 1 ============
lines.append("-- ============================================================")
lines.append("-- STEP 1: SCHEMA CREATION")
lines.append("-- ============================================================")
lines.append("DROP SCHEMA IF EXISTS portfolio_analysis;")
lines.append("CREATE SCHEMA portfolio_analysis;")
lines.append("USE portfolio_analysis;")
lines.append("")

# ============ STEP 2 ============
lines.append("-- ============================================================")
lines.append("-- STEP 2: TABLE CREATION")
lines.append("-- ============================================================")
lines.append("DROP TABLE IF EXISTS stock_prices;")
lines.append("CREATE TABLE stock_prices (")
lines.append("    id            INT AUTO_INCREMENT PRIMARY KEY,")
lines.append("    ticker        VARCHAR(10)    NOT NULL,")
lines.append("    price_date    DATE           NOT NULL,")
lines.append("    open_price    DECIMAL(12,4)  NOT NULL,")
lines.append("    high_price    DECIMAL(12,4)  NOT NULL,")
lines.append("    low_price     DECIMAL(12,4)  NOT NULL,")
lines.append("    close_price   DECIMAL(12,4)  NOT NULL,")
lines.append("    adj_close     DECIMAL(12,4)  NOT NULL,")
lines.append("    volume        BIGINT         NOT NULL,")
lines.append("    UNIQUE INDEX idx_ticker_date (ticker, price_date),")
lines.append("    INDEX idx_date (price_date),")
lines.append("    INDEX idx_ticker (ticker)")
lines.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
lines.append("")

# ============ STEP 3 ============
lines.append("-- ============================================================")
lines.append("-- STEP 3: DATA INSERTS (4,340 rows)")
lines.append("-- ============================================================")
lines.append(user_inserts)
lines.append("")

# ============ STEP 4: VERIFICATION ============
lines.append("-- ============================================================")
lines.append("-- STEP 4: DATA VERIFICATION")
lines.append("-- ============================================================")
lines.append("")
lines.append("SELECT ticker,")
lines.append("       COUNT(*)        AS row_count,")
lines.append("       MIN(price_date) AS first_date,")
lines.append("       MAX(price_date) AS last_date")
lines.append("FROM stock_prices")
lines.append("GROUP BY ticker")
lines.append("ORDER BY ticker;")
lines.append("")
lines.append("SELECT COUNT(*) AS total_rows FROM stock_prices;")
lines.append("")

# ============================================================
# QUESTION 1 (20 pts)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- QUESTION 1 (20 pts):")
lines.append("-- What is the most recent 12M, 18M, 24M return for each")
lines.append("-- security and for the entire portfolio?")
lines.append("--")
lines.append("-- Method: (end_price - start_price) / start_price * 100")
lines.append("-- Uses the most recent trading date as the endpoint.")
lines.append("-- Portfolio return = weighted sum of individual returns.")
lines.append("-- ============================================================")
lines.append("")
lines.append("WITH end_p AS (")
lines.append("  SELECT ticker, adj_close")
lines.append("  FROM stock_prices")
lines.append("  WHERE price_date = (SELECT MAX(price_date) FROM stock_prices)")
lines.append("),")
lines.append("start_12 AS (")
lines.append("  SELECT sp.ticker, sp.adj_close")
lines.append("  FROM stock_prices sp")
lines.append("  INNER JOIN (")
lines.append("    SELECT ticker, MIN(price_date) AS d")
lines.append("    FROM stock_prices")
lines.append("    WHERE price_date >= DATE_SUB((SELECT MAX(price_date) FROM stock_prices), INTERVAL 12 MONTH)")
lines.append("    GROUP BY ticker")
lines.append("  ) t ON sp.ticker = t.ticker AND sp.price_date = t.d")
lines.append("),")
lines.append("start_18 AS (")
lines.append("  SELECT sp.ticker, sp.adj_close")
lines.append("  FROM stock_prices sp")
lines.append("  INNER JOIN (")
lines.append("    SELECT ticker, MIN(price_date) AS d")
lines.append("    FROM stock_prices")
lines.append("    WHERE price_date >= DATE_SUB((SELECT MAX(price_date) FROM stock_prices), INTERVAL 18 MONTH)")
lines.append("    GROUP BY ticker")
lines.append("  ) t ON sp.ticker = t.ticker AND sp.price_date = t.d")
lines.append("),")
lines.append("start_24 AS (")
lines.append("  SELECT sp.ticker, sp.adj_close")
lines.append("  FROM stock_prices sp")
lines.append("  INNER JOIN (")
lines.append("    SELECT ticker, MIN(price_date) AS d")
lines.append("    FROM stock_prices")
lines.append("    WHERE price_date >= DATE_SUB((SELECT MAX(price_date) FROM stock_prices), INTERVAL 24 MONTH)")
lines.append("    GROUP BY ticker")
lines.append("  ) t ON sp.ticker = t.ticker AND sp.price_date = t.d")
lines.append(")")
lines.append("SELECT")
lines.append("  e.ticker,")
lines.append("  ROUND((e.adj_close - s12.adj_close) / s12.adj_close * 100, 2) AS return_12m_pct,")
lines.append("  ROUND((e.adj_close - s18.adj_close) / s18.adj_close * 100, 2) AS return_18m_pct,")
lines.append("  ROUND((e.adj_close - s24.adj_close) / s24.adj_close * 100, 2) AS return_24m_pct")
lines.append("FROM end_p e")
lines.append("JOIN start_12 s12 ON e.ticker = s12.ticker")
lines.append("JOIN start_18 s18 ON e.ticker = s18.ticker")
lines.append("JOIN start_24 s24 ON e.ticker = s24.ticker")
lines.append("")
lines.append("UNION ALL")
lines.append("")
lines.append("SELECT")
lines.append("  'PORTFOLIO' AS ticker,")
lines.append("  ROUND(SUM((e.adj_close - s12.adj_close) / s12.adj_close * 100 *")
lines.append("    CASE e.ticker WHEN 'IXN' THEN 0.175 WHEN 'QQQ' THEN 0.221 WHEN 'IEF' THEN 0.285")
lines.append("                  WHEN 'VNQ' THEN 0.089 WHEN 'GLD' THEN 0.230 END), 2) AS return_12m_pct,")
lines.append("  ROUND(SUM((e.adj_close - s18.adj_close) / s18.adj_close * 100 *")
lines.append("    CASE e.ticker WHEN 'IXN' THEN 0.175 WHEN 'QQQ' THEN 0.221 WHEN 'IEF' THEN 0.285")
lines.append("                  WHEN 'VNQ' THEN 0.089 WHEN 'GLD' THEN 0.230 END), 2) AS return_18m_pct,")
lines.append("  ROUND(SUM((e.adj_close - s24.adj_close) / s24.adj_close * 100 *")
lines.append("    CASE e.ticker WHEN 'IXN' THEN 0.175 WHEN 'QQQ' THEN 0.221 WHEN 'IEF' THEN 0.285")
lines.append("                  WHEN 'VNQ' THEN 0.089 WHEN 'GLD' THEN 0.230 END), 2) AS return_24m_pct")
lines.append("FROM end_p e")
lines.append("JOIN start_12 s12 ON e.ticker = s12.ticker")
lines.append("JOIN start_18 s18 ON e.ticker = s18.ticker")
lines.append("JOIN start_24 s24 ON e.ticker = s24.ticker;")
lines.append("")

# ============================================================
# QUESTION 2 (20 pts)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- QUESTION 2 (20 pts):")
lines.append("-- What are the correlations between your assets?")
lines.append("--")
lines.append("-- Part A: Pairwise Pearson correlations (all 10 pairs)")
lines.append("--   Formula: (AVG(x*y) - AVG(x)*AVG(y)) / (STD(x)*STD(y))")
lines.append("--")
lines.append("-- Part B: Variance fallback (if corr() is unavailable)")
lines.append("--   Shows variance and std dev per ticker for comparison.")
lines.append("-- ============================================================")
lines.append("")
lines.append("-- Part A: Pairwise correlations")
lines.append("")
lines.append("WITH r AS (")
lines.append("  SELECT ticker, price_date,")
lines.append("         (adj_close - LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date))")
lines.append("         / LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date) AS ror")
lines.append("  FROM portfolio_analysis.stock_prices")
lines.append("),")
lines.append("daily AS (")
lines.append("  SELECT price_date,")
lines.append("         MAX(CASE WHEN ticker='IXN' THEN ror END) AS ixn_ror,")
lines.append("         MAX(CASE WHEN ticker='QQQ' THEN ror END) AS qqq_ror,")
lines.append("         MAX(CASE WHEN ticker='IEF' THEN ror END) AS ief_ror,")
lines.append("         MAX(CASE WHEN ticker='VNQ' THEN ror END) AS vnq_ror,")
lines.append("         MAX(CASE WHEN ticker='GLD' THEN ror END) AS gld_ror")
lines.append("  FROM r")
lines.append("  WHERE ror IS NOT NULL")
lines.append("  GROUP BY price_date")
lines.append("  HAVING MAX(CASE WHEN ticker='IXN' THEN ror END) IS NOT NULL")
lines.append(")")
lines.append("SELECT 'IXN-QQQ' AS pair, ROUND((AVG(ixn_ror*qqq_ror) - AVG(ixn_ror)*AVG(qqq_ror)) / (STD(ixn_ror)*STD(qqq_ror)), 3) AS correlation FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IXN-IEF', ROUND((AVG(ixn_ror*ief_ror) - AVG(ixn_ror)*AVG(ief_ror)) / (STD(ixn_ror)*STD(ief_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IXN-VNQ', ROUND((AVG(ixn_ror*vnq_ror) - AVG(ixn_ror)*AVG(vnq_ror)) / (STD(ixn_ror)*STD(vnq_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IXN-GLD', ROUND((AVG(ixn_ror*gld_ror) - AVG(ixn_ror)*AVG(gld_ror)) / (STD(ixn_ror)*STD(gld_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'QQQ-IEF', ROUND((AVG(qqq_ror*ief_ror) - AVG(qqq_ror)*AVG(ief_ror)) / (STD(qqq_ror)*STD(ief_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'QQQ-VNQ', ROUND((AVG(qqq_ror*vnq_ror) - AVG(qqq_ror)*AVG(vnq_ror)) / (STD(qqq_ror)*STD(vnq_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'QQQ-GLD', ROUND((AVG(qqq_ror*gld_ror) - AVG(qqq_ror)*AVG(gld_ror)) / (STD(qqq_ror)*STD(gld_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IEF-VNQ', ROUND((AVG(ief_ror*vnq_ror) - AVG(ief_ror)*AVG(vnq_ror)) / (STD(ief_ror)*STD(vnq_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IEF-GLD', ROUND((AVG(ief_ror*gld_ror) - AVG(ief_ror)*AVG(gld_ror)) / (STD(ief_ror)*STD(gld_ror)), 3) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'VNQ-GLD', ROUND((AVG(vnq_ror*gld_ror) - AVG(vnq_ror)*AVG(gld_ror)) / (STD(vnq_ror)*STD(gld_ror)), 3) FROM daily")
lines.append("ORDER BY pair;")
lines.append("")

lines.append("-- Part B: Variance fallback (per-ticker variance and sigma)")
lines.append("")
lines.append("WITH r AS (")
lines.append("  SELECT ticker, price_date,")
lines.append("         (adj_close - LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date))")
lines.append("         / LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date) AS ror")
lines.append("  FROM portfolio_analysis.stock_prices")
lines.append(")")
lines.append("SELECT ticker,")
lines.append("       COUNT(*)                                   AS n_obs,")
lines.append("       ROUND(AVG(ror)*252*100, 4)                 AS ann_mean_return_pct,")
lines.append("       ROUND(VARIANCE(ror), 8)                    AS daily_variance,")
lines.append("       ROUND(STD(ror), 6)                         AS daily_std_dev,")
lines.append("       ROUND(STD(ror)*SQRT(252)*100, 2)           AS ann_sigma_pct")
lines.append("FROM r")
lines.append("WHERE ror IS NOT NULL")
lines.append("GROUP BY ticker")
lines.append("ORDER BY ticker;")
lines.append("")

# ============================================================
# QUESTION 3 (20 pts)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- QUESTION 3 (20 pts):")
lines.append("-- What is the most recent 12M sigma (risk) for each security")
lines.append("-- and for the entire portfolio?")
lines.append("--")
lines.append("-- Sigma = STD(daily_return) * SQRT(252) * 100")
lines.append("-- Filtered to the most recent 12 months of trading data.")
lines.append("-- Portfolio sigma uses the weighted daily portfolio return,")
lines.append("-- which captures the diversification effect.")
lines.append("-- ============================================================")
lines.append("")
lines.append("WITH r AS (")
lines.append("  SELECT ticker, price_date,")
lines.append("         (adj_close - LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date))")
lines.append("         / LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date) AS ror")
lines.append("  FROM portfolio_analysis.stock_prices")
lines.append("),")
lines.append("daily AS (")
lines.append("  SELECT price_date,")
lines.append("         MAX(CASE WHEN ticker='IXN' THEN ror END) AS ixn_ror,")
lines.append("         MAX(CASE WHEN ticker='QQQ' THEN ror END) AS qqq_ror,")
lines.append("         MAX(CASE WHEN ticker='IEF' THEN ror END) AS ief_ror,")
lines.append("         MAX(CASE WHEN ticker='VNQ' THEN ror END) AS vnq_ror,")
lines.append("         MAX(CASE WHEN ticker='GLD' THEN ror END) AS gld_ror,")
lines.append("         0.175*MAX(CASE WHEN ticker='IXN' THEN ror END)")
lines.append("       + 0.221*MAX(CASE WHEN ticker='QQQ' THEN ror END)")
lines.append("       + 0.285*MAX(CASE WHEN ticker='IEF' THEN ror END)")
lines.append("       + 0.089*MAX(CASE WHEN ticker='VNQ' THEN ror END)")
lines.append("       + 0.230*MAX(CASE WHEN ticker='GLD' THEN ror END) AS port_ror")
lines.append("  FROM r")
lines.append("  WHERE ror IS NOT NULL")
lines.append("    AND price_date >= DATE_SUB((SELECT MAX(price_date) FROM portfolio_analysis.stock_prices), INTERVAL 12 MONTH)")
lines.append("  GROUP BY price_date")
lines.append("  HAVING MAX(CASE WHEN ticker='IXN' THEN ror END) IS NOT NULL")
lines.append(")")
lines.append("SELECT 'IXN' AS ticker, ROUND(STD(ixn_ror)*SQRT(252)*100, 2) AS sigma_12m_pct FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'QQQ',           ROUND(STD(qqq_ror)*SQRT(252)*100, 2) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IEF',           ROUND(STD(ief_ror)*SQRT(252)*100, 2) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'VNQ',           ROUND(STD(vnq_ror)*SQRT(252)*100, 2) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'GLD',           ROUND(STD(gld_ror)*SQRT(252)*100, 2) FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'PORTFOLIO',     ROUND(STD(port_ror)*SQRT(252)*100, 2) FROM daily;")
lines.append("")

# ============================================================
# QUESTION 4 (20 pts)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- QUESTION 4 (20 pts):")
lines.append("-- Based on Q1-Q3, which holdings would you sell, which would")
lines.append("-- you buy? Any outside securities to add?")
lines.append("--")
lines.append("-- This query combines 12M return, 12M sigma, and Sharpe ratio")
lines.append("-- for each ticker into one summary table to support the")
lines.append("-- buy/sell/hold decision.")
lines.append("--")
lines.append("-- Sharpe ratio = AVG(daily_ror) / STD(daily_ror) * SQRT(252)")
lines.append("-- Higher Sharpe = better risk-adjusted return.")
lines.append("-- ============================================================")
lines.append("")
lines.append("WITH r AS (")
lines.append("  SELECT ticker, price_date,")
lines.append("         (adj_close - LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date))")
lines.append("         / LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date) AS ror")
lines.append("  FROM portfolio_analysis.stock_prices")
lines.append("),")
lines.append("daily AS (")
lines.append("  SELECT price_date,")
lines.append("         MAX(CASE WHEN ticker='IXN' THEN ror END) AS ixn_ror,")
lines.append("         MAX(CASE WHEN ticker='QQQ' THEN ror END) AS qqq_ror,")
lines.append("         MAX(CASE WHEN ticker='IEF' THEN ror END) AS ief_ror,")
lines.append("         MAX(CASE WHEN ticker='VNQ' THEN ror END) AS vnq_ror,")
lines.append("         MAX(CASE WHEN ticker='GLD' THEN ror END) AS gld_ror,")
lines.append("         0.175*MAX(CASE WHEN ticker='IXN' THEN ror END)")
lines.append("       + 0.221*MAX(CASE WHEN ticker='QQQ' THEN ror END)")
lines.append("       + 0.285*MAX(CASE WHEN ticker='IEF' THEN ror END)")
lines.append("       + 0.089*MAX(CASE WHEN ticker='VNQ' THEN ror END)")
lines.append("       + 0.230*MAX(CASE WHEN ticker='GLD' THEN ror END) AS port_ror")
lines.append("  FROM r")
lines.append("  WHERE ror IS NOT NULL")
lines.append("    AND price_date >= DATE_SUB((SELECT MAX(price_date) FROM portfolio_analysis.stock_prices), INTERVAL 12 MONTH)")
lines.append("  GROUP BY price_date")
lines.append("  HAVING MAX(CASE WHEN ticker='IXN' THEN ror END) IS NOT NULL")
lines.append(")")
lines.append("SELECT 'IXN' AS ticker,")
lines.append("       17.5  AS current_weight_pct,")
lines.append("       ROUND(AVG(ixn_ror)*252*100, 2)                        AS ann_return_12m_pct,")
lines.append("       ROUND(STD(ixn_ror)*SQRT(252)*100, 2)                  AS sigma_12m_pct,")
lines.append("       ROUND(AVG(ixn_ror)/STD(ixn_ror)*SQRT(252), 3)         AS sharpe_12m")
lines.append("FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'QQQ', 22.1,")
lines.append("       ROUND(AVG(qqq_ror)*252*100, 2),")
lines.append("       ROUND(STD(qqq_ror)*SQRT(252)*100, 2),")
lines.append("       ROUND(AVG(qqq_ror)/STD(qqq_ror)*SQRT(252), 3)")
lines.append("FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'IEF', 28.5,")
lines.append("       ROUND(AVG(ief_ror)*252*100, 2),")
lines.append("       ROUND(STD(ief_ror)*SQRT(252)*100, 2),")
lines.append("       ROUND(AVG(ief_ror)/STD(ief_ror)*SQRT(252), 3)")
lines.append("FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'VNQ', 8.9,")
lines.append("       ROUND(AVG(vnq_ror)*252*100, 2),")
lines.append("       ROUND(STD(vnq_ror)*SQRT(252)*100, 2),")
lines.append("       ROUND(AVG(vnq_ror)/STD(vnq_ror)*SQRT(252), 3)")
lines.append("FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'GLD', 23.0,")
lines.append("       ROUND(AVG(gld_ror)*252*100, 2),")
lines.append("       ROUND(STD(gld_ror)*SQRT(252)*100, 2),")
lines.append("       ROUND(AVG(gld_ror)/STD(gld_ror)*SQRT(252), 3)")
lines.append("FROM daily")
lines.append("UNION ALL")
lines.append("SELECT 'PORTFOLIO', 100.0,")
lines.append("       ROUND(AVG(port_ror)*252*100, 2),")
lines.append("       ROUND(STD(port_ror)*SQRT(252)*100, 2),")
lines.append("       ROUND(AVG(port_ror)/STD(port_ror)*SQRT(252), 3)")
lines.append("FROM daily;")
lines.append("")
lines.append("-- Use the results above to determine:")
lines.append("-- BUY:  tickers with high Sharpe ratio and strong 12M return")
lines.append("-- HOLD: tickers with moderate performance or diversification value")
lines.append("-- SELL: tickers with negative Sharpe or poor risk-adjusted return")
lines.append("-- ADD:  consider adding an emerging markets ETF (e.g., IEMG)")
lines.append("--       for geographic diversification outside US tech/bonds")
lines.append("")

# ============================================================
# QUESTION 5 (20 pts)
# ============================================================
lines.append("-- ============================================================")
lines.append("-- QUESTION 5 (20 pts):")
lines.append("-- How will portfolio risk and expected returns change after")
lines.append("-- rebalancing (selling and buying)?")
lines.append("--")
lines.append("-- Compares CURRENT mix vs. RECOMMENDED target mix.")
lines.append("-- Current:     IXN 17.5%  QQQ 22.1%  IEF 28.5%  VNQ 8.9%  GLD 23.0%")
lines.append("-- Recommended: IXN 20.0%  QQQ 25.0%  IEF 25.0%  VNQ 7.0%  GLD 23.0%")
lines.append("--")
lines.append("-- Part A: Side-by-side annual return, risk, Sharpe by year")
lines.append("-- Part B: Diversification benefit comparison")
lines.append("-- ============================================================")
lines.append("")
lines.append("-- Part A: Current mix vs. Recommended mix by year")
lines.append("")
lines.append("WITH r AS (")
lines.append("  SELECT ticker, price_date,")
lines.append("         (adj_close - LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date))")
lines.append("         / LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date) AS ror")
lines.append("  FROM portfolio_analysis.stock_prices")
lines.append("),")
lines.append("daily AS (")
lines.append("  SELECT price_date,")
lines.append("         YEAR(price_date) AS yr,")
lines.append("         -- Current portfolio mix")
lines.append("         0.175*MAX(CASE WHEN ticker='IXN' THEN ror END)")
lines.append("       + 0.221*MAX(CASE WHEN ticker='QQQ' THEN ror END)")
lines.append("       + 0.285*MAX(CASE WHEN ticker='IEF' THEN ror END)")
lines.append("       + 0.089*MAX(CASE WHEN ticker='VNQ' THEN ror END)")
lines.append("       + 0.230*MAX(CASE WHEN ticker='GLD' THEN ror END) AS curr_ror,")
lines.append("         -- Recommended target mix")
lines.append("         0.200*MAX(CASE WHEN ticker='IXN' THEN ror END)")
lines.append("       + 0.250*MAX(CASE WHEN ticker='QQQ' THEN ror END)")
lines.append("       + 0.250*MAX(CASE WHEN ticker='IEF' THEN ror END)")
lines.append("       + 0.070*MAX(CASE WHEN ticker='VNQ' THEN ror END)")
lines.append("       + 0.230*MAX(CASE WHEN ticker='GLD' THEN ror END) AS rec_ror")
lines.append("  FROM r")
lines.append("  WHERE ror IS NOT NULL")
lines.append("  GROUP BY price_date")
lines.append("  HAVING MAX(CASE WHEN ticker='IXN' THEN ror END) IS NOT NULL")
lines.append(")")
lines.append("SELECT yr,")
lines.append("       'CURRENT MIX' AS portfolio,")
lines.append("       ROUND(AVG(curr_ror)*252*100, 2)                        AS ann_return_pct,")
lines.append("       ROUND(STD(curr_ror)*SQRT(252)*100, 2)                  AS ann_risk_pct,")
lines.append("       ROUND(AVG(curr_ror)/STD(curr_ror)*SQRT(252), 3)        AS ann_sharpe")
lines.append("FROM daily GROUP BY yr")
lines.append("UNION ALL")
lines.append("SELECT yr,")
lines.append("       'RECOMMENDED TARGET MIX',")
lines.append("       ROUND(AVG(rec_ror)*252*100, 2),")
lines.append("       ROUND(STD(rec_ror)*SQRT(252)*100, 2),")
lines.append("       ROUND(AVG(rec_ror)/STD(rec_ror)*SQRT(252), 3)")
lines.append("FROM daily GROUP BY yr")
lines.append("ORDER BY yr, portfolio;")
lines.append("")

lines.append("-- Part B: Diversification benefit comparison")
lines.append("")
lines.append("WITH r AS (")
lines.append("  SELECT ticker, price_date,")
lines.append("         (adj_close - LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date))")
lines.append("         / LAG(adj_close) OVER (PARTITION BY ticker ORDER BY price_date) AS ror")
lines.append("  FROM portfolio_analysis.stock_prices")
lines.append("),")
lines.append("per_ticker AS (")
lines.append("  SELECT ticker, STD(ror)*SQRT(252)*100 AS ann_risk_pct")
lines.append("  FROM r")
lines.append("  WHERE ror IS NOT NULL")
lines.append("  GROUP BY ticker")
lines.append("),")
lines.append("daily AS (")
lines.append("  SELECT price_date,")
lines.append("         0.175*MAX(CASE WHEN ticker='IXN' THEN ror END)")
lines.append("       + 0.221*MAX(CASE WHEN ticker='QQQ' THEN ror END)")
lines.append("       + 0.285*MAX(CASE WHEN ticker='IEF' THEN ror END)")
lines.append("       + 0.089*MAX(CASE WHEN ticker='VNQ' THEN ror END)")
lines.append("       + 0.230*MAX(CASE WHEN ticker='GLD' THEN ror END) AS curr_ror,")
lines.append("         0.200*MAX(CASE WHEN ticker='IXN' THEN ror END)")
lines.append("       + 0.250*MAX(CASE WHEN ticker='QQQ' THEN ror END)")
lines.append("       + 0.250*MAX(CASE WHEN ticker='IEF' THEN ror END)")
lines.append("       + 0.070*MAX(CASE WHEN ticker='VNQ' THEN ror END)")
lines.append("       + 0.230*MAX(CASE WHEN ticker='GLD' THEN ror END) AS rec_ror")
lines.append("  FROM r")
lines.append("  WHERE ror IS NOT NULL")
lines.append("  GROUP BY price_date")
lines.append("  HAVING MAX(CASE WHEN ticker='IXN' THEN ror END) IS NOT NULL")
lines.append(")")
lines.append("SELECT")
lines.append("  ROUND((SELECT AVG(ann_risk_pct) FROM per_ticker), 2)         AS naive_avg_individual_risk_pct,")
lines.append("  ROUND((SELECT STD(curr_ror)*SQRT(252)*100 FROM daily), 2)    AS current_mix_risk_pct,")
lines.append("  ROUND((SELECT STD(rec_ror)*SQRT(252)*100 FROM daily), 2)     AS recommended_mix_risk_pct,")
lines.append("  ROUND((SELECT AVG(ann_risk_pct) FROM per_ticker)")
lines.append("        - (SELECT STD(curr_ror)*SQRT(252)*100 FROM daily), 2)  AS current_diversification_benefit_pts,")
lines.append("  ROUND((SELECT AVG(ann_risk_pct) FROM per_ticker)")
lines.append("        - (SELECT STD(rec_ror)*SQRT(252)*100 FROM daily), 2)   AS recommended_diversification_benefit_pts;")
lines.append("")
lines.append("-- ============================================================")
lines.append("-- END OF SCRIPT")
lines.append("-- ============================================================")

with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"SQL file written: {output_path}")
print(f"Total lines: {len(lines)}")
