import yfinance as yf
import datetime

tickers = ['IXN', 'QQQ', 'IEF', 'VNQ', 'GLD']
weights = {'IXN': 17.5, 'QQQ': 22.1, 'IEF': 28.5, 'VNQ': 8.9, 'GLD': 23.0}

start = '2023-01-01'
end = datetime.date.today().isoformat()

print(f"Downloading data from {start} to {end}...")

all_data = {}
for t in tickers:
    df = yf.download(t, start=start, end=end, auto_adjust=False, progress=False)
    # Flatten MultiIndex columns if present
    if hasattr(df.columns, 'levels'):
        df.columns = [c[0] if isinstance(c, tuple) else c for c in df.columns]
    all_data[t] = df
    print(f"  {t}: {len(df)} rows")

# Build the SQL file
lines = []

# ============================================================
# SECTION 1: SCHEMA + TABLE
# ============================================================
lines.append("-- ============================================================")
lines.append("-- PORTFOLIO ANALYSIS - COMPLETE SQL SCRIPT")
lines.append("-- Generated: " + datetime.date.today().isoformat())
lines.append("-- Client: UHNW $95M Portfolio - Palo Alto")
lines.append("-- Assets: IXN (17.5%), QQQ (22.1%), IEF (28.5%), VNQ (8.9%), GLD (23.0%)")
lines.append("-- ============================================================")
lines.append("")
lines.append("-- ============================================================")
lines.append("-- STEP 1: SCHEMA CREATION")
lines.append("-- ============================================================")
lines.append("DROP SCHEMA IF EXISTS portfolio_analysis;")
lines.append("CREATE SCHEMA portfolio_analysis;")
lines.append("USE portfolio_analysis;")
lines.append("")

lines.append("-- ============================================================")
lines.append("-- STEP 2: TABLE CREATION")
lines.append("-- ============================================================")
lines.append("DROP TABLE IF EXISTS stock_prices;")
lines.append("CREATE TABLE stock_prices (")
lines.append("    id            INT AUTO_INCREMENT PRIMARY KEY,")
lines.append("    ticker        VARCHAR(10)    NOT NULL,")
lines.append("    price_date    DATE           NOT NULL,")
lines.append("    open_price    DECIMAL(12,4)  NOT NULL,")
lines.append("    high_price    DECIMAL(12,4)  NOT NULL,")
lines.append("    low_price     DECIMAL(12,4)  NOT NULL,")
lines.append("    close_price   DECIMAL(12,4)  NOT NULL,")
lines.append("    adj_close     DECIMAL(12,4)  NOT NULL,")
lines.append("    volume        BIGINT         NOT NULL,")
lines.append("    UNIQUE INDEX idx_ticker_date (ticker, price_date),")
lines.append("    INDEX idx_date (price_date),")
lines.append("    INDEX idx_ticker (ticker)")
lines.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
lines.append("")

# ============================================================
# SECTION 3: INSERT STATEMENTS
# ============================================================
lines.append("-- ============================================================")
lines.append("-- STEP 3: DATA INSERTS")
lines.append("-- ============================================================")

for t in tickers:
    df = all_data[t]
    lines.append(f"")
    lines.append(f"-- {t} data ({len(df)} rows)")

    # Batch inserts for performance (500 rows per INSERT)
    batch_size = 500
    rows_for_ticker = []

    for idx, row in df.iterrows():
        date_str = idx.strftime('%Y-%m-%d') if hasattr(idx, 'strftime') else str(idx)[:10]
        open_p = round(float(row['Open']), 4)
        high_p = round(float(row['High']), 4)
        low_p = round(float(row['Low']), 4)
        close_p = round(float(row['Close']), 4)
        adj_p = round(float(row['Adj Close']), 4)
        vol = int(row['Volume'])
        rows_for_ticker.append(
            f"('{t}', '{date_str}', {open_p}, {high_p}, {low_p}, {close_p}, {adj_p}, {vol})"
        )

    # Write in batches
    for i in range(0, len(rows_for_ticker), batch_size):
        batch = rows_for_ticker[i:i+batch_size]
        lines.append("INSERT INTO stock_prices (ticker, price_date, open_price, high_price, low_price, close_price, adj_close, volume) VALUES")
        lines.append(",\n".join(batch) + ";")
        lines.append("")

# ============================================================
# SECTION 4: VERIFICATION QUERIES
# ============================================================
lines.append("-- ============================================================")
lines.append("-- STEP 4: VERIFICATION QUERIES")
lines.append("-- ============================================================")
lines.append("")
lines.append("-- Row counts per ticker")
lines.append("SELECT ticker, COUNT(*) AS row_count, MIN(price_date) AS first_date, MAX(price_date) AS last_date")
lines.append("FROM stock_prices")
lines.append("GROUP BY ticker")
lines.append("ORDER BY ticker;")
lines.append("")
lines.append("-- Total row count")
lines.append("SELECT COUNT(*) AS total_rows FROM stock_prices;")
lines.append("")
lines.append("-- Sample data (latest 5 rows per ticker)")
lines.append("SELECT sp.*")
lines.append("FROM stock_prices sp")
lines.append("INNER JOIN (")
lines.append("    SELECT ticker, MAX(price_date) AS max_date FROM stock_prices GROUP BY ticker")
lines.append(") latest ON sp.ticker = latest.ticker AND sp.price_date >= DATE_SUB(latest.max_date, INTERVAL 7 DAY)")
lines.append("ORDER BY sp.ticker, sp.price_date DESC;")
lines.append("")
lines.append("-- Check for gaps or duplicates")
lines.append("SELECT ticker, price_date, COUNT(*) AS cnt")
lines.append("FROM stock_prices")
lines.append("GROUP BY ticker, price_date")
lines.append("HAVING cnt > 1;")
lines.append("")

# ============================================================
# SECTION 5: PORTFOLIO WEIGHTS REFERENCE TABLE
# ============================================================
lines.append("-- ============================================================")
lines.append("-- STEP 5: PORTFOLIO WEIGHTS REFERENCE TABLE")
lines.append("-- ============================================================")
lines.append("DROP TABLE IF EXISTS portfolio_weights;")
lines.append("CREATE TABLE portfolio_weights (")
lines.append("    ticker          VARCHAR(10) PRIMARY KEY,")
lines.append("    weight_pct      DECIMAL(5,2) NOT NULL,")
lines.append("    asset_class     VARCHAR(50)  NOT NULL,")
lines.append("    description     VARCHAR(100) NOT NULL")
lines.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
lines.append("")
lines.append("INSERT INTO portfolio_weights (ticker, weight_pct, asset_class, description) VALUES")
lines.append("('IXN', 17.50, 'Equity - Global Tech',    'iShares Global Tech ETF'),")
lines.append("('QQQ', 22.10, 'Equity - US Large Cap',   'Invesco QQQ Trust (NASDAQ 100)'),")
lines.append("('IEF', 28.50, 'Fixed Income - US Govt',  'iShares 7-10 Year Treasury Bond ETF'),")
lines.append("('VNQ',  8.90, 'Real Estate - US REITs',  'Vanguard Real Estate ETF'),")
lines.append("('GLD', 23.00, 'Commodities - Gold',      'SPDR Gold Shares');")
lines.append("")

# ============================================================
# SECTION 6: STORED PROCEDURES
# ============================================================
lines.append("-- ============================================================")
lines.append("-- STEP 6: STORED PROCEDURES")
lines.append("-- ============================================================")
lines.append("")

# ---------- SP 1: PORTFOLIO RETURNS ----------
lines.append("-- ------------------------------------------------------------")
lines.append("-- SP 1: sp_portfolio_returns")
lines.append("-- Calculates % return for each ticker AND the weighted portfolio")
lines.append("-- for a given lookback period (in months).")
lines.append("-- Logic: (end_adj_close - start_adj_close) / start_adj_close * 100")
lines.append("-- Uses the most recent trading date as the end date.")
lines.append("-- ------------------------------------------------------------")
lines.append("DROP PROCEDURE IF EXISTS sp_portfolio_returns;")
lines.append("DELIMITER //")
lines.append("CREATE PROCEDURE sp_portfolio_returns(IN p_months INT)")
lines.append("BEGIN")
lines.append("    DECLARE v_end_date DATE;")
lines.append("    DECLARE v_start_date DATE;")
lines.append("")
lines.append("    -- Find the most recent trading date in the dataset")
lines.append("    SELECT MAX(price_date) INTO v_end_date FROM stock_prices;")
lines.append("    SET v_start_date = DATE_SUB(v_end_date, INTERVAL p_months MONTH);")
lines.append("")
lines.append("    -- Create temp table with returns per ticker")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_returns;")
lines.append("    CREATE TEMPORARY TABLE tmp_returns AS")
lines.append("    SELECT")
lines.append("        e.ticker,")
lines.append("        p_months AS period_months,")
lines.append("        s.adj_close AS start_price,")
lines.append("        e.adj_close AS end_price,")
lines.append("        ROUND((e.adj_close - s.adj_close) / s.adj_close * 100, 4) AS return_pct")
lines.append("    FROM (")
lines.append("        -- End prices: closest trading day to or before v_end_date")
lines.append("        SELECT ticker, adj_close, price_date")
lines.append("        FROM stock_prices sp1")
lines.append("        WHERE price_date = (")
lines.append("            SELECT MAX(price_date) FROM stock_prices sp2")
lines.append("            WHERE sp2.ticker = sp1.ticker AND sp2.price_date <= v_end_date")
lines.append("        )")
lines.append("    ) e")
lines.append("    INNER JOIN (")
lines.append("        -- Start prices: closest trading day on or after v_start_date")
lines.append("        SELECT ticker, adj_close, price_date")
lines.append("        FROM stock_prices sp3")
lines.append("        WHERE price_date = (")
lines.append("            SELECT MIN(price_date) FROM stock_prices sp4")
lines.append("            WHERE sp4.ticker = sp3.ticker AND sp4.price_date >= v_start_date")
lines.append("        )")
lines.append("    ) s ON e.ticker = s.ticker;")
lines.append("")
lines.append("    -- Output: individual ticker returns + weighted portfolio return")
lines.append("    SELECT")
lines.append("        r.ticker,")
lines.append("        r.period_months,")
lines.append("        r.start_price,")
lines.append("        r.end_price,")
lines.append("        r.return_pct,")
lines.append("        pw.weight_pct,")
lines.append("        ROUND(r.return_pct * pw.weight_pct / 100, 4) AS weighted_return_pct")
lines.append("    FROM tmp_returns r")
lines.append("    JOIN portfolio_weights pw ON r.ticker = pw.ticker")
lines.append("    UNION ALL")
lines.append("    SELECT")
lines.append("        'PORTFOLIO' AS ticker,")
lines.append("        p_months AS period_months,")
lines.append("        NULL AS start_price,")
lines.append("        NULL AS end_price,")
lines.append("        ROUND(SUM(r.return_pct * pw.weight_pct / 100), 4) AS return_pct,")
lines.append("        100.00 AS weight_pct,")
lines.append("        ROUND(SUM(r.return_pct * pw.weight_pct / 100), 4) AS weighted_return_pct")
lines.append("    FROM tmp_returns r")
lines.append("    JOIN portfolio_weights pw ON r.ticker = pw.ticker;")
lines.append("")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_returns;")
lines.append("END //")
lines.append("DELIMITER ;")
lines.append("")

# ---------- SP 2: ASSET CORRELATIONS ----------
lines.append("-- ------------------------------------------------------------")
lines.append("-- SP 2: sp_asset_correlations")
lines.append("-- Calculates pairwise Pearson correlation between daily returns")
lines.append("-- of all 5 assets. MySQL lacks a built-in CORR() function, so")
lines.append("-- we compute it manually using the Pearson formula:")
lines.append("-- r = [n*SUM(xy) - SUM(x)*SUM(y)] /")
lines.append("--     SQRT([n*SUM(x^2) - SUM(x)^2] * [n*SUM(y^2) - SUM(y)^2])")
lines.append("-- Also outputs variance (sigma^2) per ticker as a fallback.")
lines.append("-- ------------------------------------------------------------")
lines.append("DROP PROCEDURE IF EXISTS sp_asset_correlations;")
lines.append("DELIMITER //")
lines.append("CREATE PROCEDURE sp_asset_correlations()")
lines.append("BEGIN")
lines.append("    -- Step 1: Calculate daily returns for each ticker")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_daily_returns;")
lines.append("    CREATE TEMPORARY TABLE tmp_daily_returns AS")
lines.append("    SELECT")
lines.append("        sp.ticker,")
lines.append("        sp.price_date,")
lines.append("        (sp.adj_close - prev.adj_close) / prev.adj_close * 100 AS daily_return")
lines.append("    FROM stock_prices sp")
lines.append("    INNER JOIN stock_prices prev")
lines.append("        ON sp.ticker = prev.ticker")
lines.append("        AND prev.price_date = (")
lines.append("            SELECT MAX(price_date)")
lines.append("            FROM stock_prices sp5")
lines.append("            WHERE sp5.ticker = sp.ticker AND sp5.price_date < sp.price_date")
lines.append("        );")
lines.append("")
lines.append("    -- Add index for join performance")
lines.append("    ALTER TABLE tmp_daily_returns ADD INDEX idx_tmp_td (ticker, price_date);")
lines.append("")
lines.append("    -- Step 2: Pairwise Pearson correlation")
lines.append("    -- Self-join daily returns on matching dates for all ticker pairs")
lines.append("    SELECT")
lines.append("        a.ticker AS ticker_a,")
lines.append("        b.ticker AS ticker_b,")
lines.append("        COUNT(*)  AS n_obs,")
lines.append("        ROUND(")
lines.append("            (COUNT(*) * SUM(a.daily_return * b.daily_return) - SUM(a.daily_return) * SUM(b.daily_return))")
lines.append("            /")
lines.append("            SQRT(")
lines.append("                (COUNT(*) * SUM(a.daily_return * a.daily_return) - POW(SUM(a.daily_return), 2))")
lines.append("                *")
lines.append("                (COUNT(*) * SUM(b.daily_return * b.daily_return) - POW(SUM(b.daily_return), 2))")
lines.append("            )")
lines.append("        , 6) AS correlation")
lines.append("    FROM tmp_daily_returns a")
lines.append("    INNER JOIN tmp_daily_returns b")
lines.append("        ON a.price_date = b.price_date")
lines.append("        AND a.ticker <= b.ticker  -- upper triangle + diagonal only")
lines.append("    GROUP BY a.ticker, b.ticker")
lines.append("    ORDER BY a.ticker, b.ticker;")
lines.append("")
lines.append("    -- Step 3: Variance (sigma^2) per ticker as fallback")
lines.append("    SELECT")
lines.append("        ticker,")
lines.append("        COUNT(*)  AS n_obs,")
lines.append("        ROUND(AVG(daily_return), 6)  AS mean_daily_return_pct,")
lines.append("        ROUND(VARIANCE(daily_return), 6) AS variance_daily,")
lines.append("        ROUND(STDDEV(daily_return), 6)   AS stddev_daily,")
lines.append("        ROUND(STDDEV(daily_return) * SQRT(252), 6) AS annualized_sigma")
lines.append("    FROM tmp_daily_returns")
lines.append("    GROUP BY ticker")
lines.append("    ORDER BY ticker;")
lines.append("")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_daily_returns;")
lines.append("END //")
lines.append("DELIMITER ;")
lines.append("")

# ---------- SP 3: PORTFOLIO SIGMA ----------
lines.append("-- ------------------------------------------------------------")
lines.append("-- SP 3: sp_portfolio_sigma")
lines.append("-- Calculates standard deviation (sigma) for each ticker over")
lines.append("-- a given lookback period (months). Also computes the portfolio-")
lines.append("-- weighted sigma using the simplified linear combination approach:")
lines.append("-- portfolio_sigma ~ SUM(weight_i * sigma_i)")
lines.append("-- For true portfolio sigma you need the covariance matrix, which")
lines.append("-- sp_asset_correlations provides for deeper analysis.")
lines.append("-- ------------------------------------------------------------")
lines.append("DROP PROCEDURE IF EXISTS sp_portfolio_sigma;")
lines.append("DELIMITER //")
lines.append("CREATE PROCEDURE sp_portfolio_sigma(IN p_months INT)")
lines.append("BEGIN")
lines.append("    DECLARE v_end_date DATE;")
lines.append("    DECLARE v_start_date DATE;")
lines.append("")
lines.append("    SELECT MAX(price_date) INTO v_end_date FROM stock_prices;")
lines.append("    SET v_start_date = DATE_SUB(v_end_date, INTERVAL p_months MONTH);")
lines.append("")
lines.append("    -- Calculate daily returns within the lookback window")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_sigma_returns;")
lines.append("    CREATE TEMPORARY TABLE tmp_sigma_returns AS")
lines.append("    SELECT")
lines.append("        sp.ticker,")
lines.append("        sp.price_date,")
lines.append("        (sp.adj_close - prev.adj_close) / prev.adj_close * 100 AS daily_return")
lines.append("    FROM stock_prices sp")
lines.append("    INNER JOIN stock_prices prev")
lines.append("        ON sp.ticker = prev.ticker")
lines.append("        AND prev.price_date = (")
lines.append("            SELECT MAX(price_date)")
lines.append("            FROM stock_prices sp6")
lines.append("            WHERE sp6.ticker = sp.ticker AND sp6.price_date < sp.price_date")
lines.append("        )")
lines.append("    WHERE sp.price_date >= v_start_date")
lines.append("      AND sp.price_date <= v_end_date;")
lines.append("")
lines.append("    -- Output: sigma per ticker + portfolio-weighted sigma")
lines.append("    SELECT")
lines.append("        sr.ticker,")
lines.append("        p_months AS period_months,")
lines.append("        COUNT(*) AS trading_days,")
lines.append("        ROUND(AVG(sr.daily_return), 6)       AS mean_daily_return_pct,")
lines.append("        ROUND(STDDEV(sr.daily_return), 6)     AS daily_sigma_pct,")
lines.append("        ROUND(STDDEV(sr.daily_return) * SQRT(252), 4) AS annualized_sigma_pct,")
lines.append("        pw.weight_pct,")
lines.append("        ROUND(STDDEV(sr.daily_return) * SQRT(252) * pw.weight_pct / 100, 4) AS weighted_sigma_pct")
lines.append("    FROM tmp_sigma_returns sr")
lines.append("    JOIN portfolio_weights pw ON sr.ticker = pw.ticker")
lines.append("    GROUP BY sr.ticker, pw.weight_pct")
lines.append("    UNION ALL")
lines.append("    SELECT")
lines.append("        'PORTFOLIO' AS ticker,")
lines.append("        p_months AS period_months,")
lines.append("        NULL AS trading_days,")
lines.append("        NULL AS mean_daily_return_pct,")
lines.append("        NULL AS daily_sigma_pct,")
lines.append("        ROUND(SUM(ann_sigma * w / 100), 4) AS annualized_sigma_pct,")
lines.append("        100.00 AS weight_pct,")
lines.append("        ROUND(SUM(ann_sigma * w / 100), 4) AS weighted_sigma_pct")
lines.append("    FROM (")
lines.append("        SELECT")
lines.append("            sr2.ticker,")
lines.append("            STDDEV(sr2.daily_return) * SQRT(252) AS ann_sigma,")
lines.append("            pw2.weight_pct AS w")
lines.append("        FROM tmp_sigma_returns sr2")
lines.append("        JOIN portfolio_weights pw2 ON sr2.ticker = pw2.ticker")
lines.append("        GROUP BY sr2.ticker, pw2.weight_pct")
lines.append("    ) sub;")
lines.append("")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_sigma_returns;")
lines.append("END //")
lines.append("DELIMITER ;")
lines.append("")

# ---------- SP 4: REBALANCING RECOMMENDATIONS ----------
lines.append("-- ------------------------------------------------------------")
lines.append("-- SP 4: sp_rebalancing_recommendations")
lines.append("-- Evaluates each asset's trailing 12-month return and sigma,")
lines.append("-- computes a risk-adjusted score (Sharpe-like: return / sigma),")
lines.append("-- and recommends SELL / HOLD / BUY / ADD_NEW.")
lines.append("-- Decision rules:")
lines.append("--   return < -5%            AND Sharpe < 0      => SELL")
lines.append("--   return between -5% & 5% OR Sharpe 0-0.5     => HOLD")
lines.append("--   return > 5%             AND Sharpe > 0.5    => BUY (increase weight)")
lines.append("--   Not currently in portfolio                   => ADD_NEW")
lines.append("-- ------------------------------------------------------------")
lines.append("DROP PROCEDURE IF EXISTS sp_rebalancing_recommendations;")
lines.append("DELIMITER //")
lines.append("CREATE PROCEDURE sp_rebalancing_recommendations()")
lines.append("BEGIN")
lines.append("    DECLARE v_end_date DATE;")
lines.append("    DECLARE v_start_date DATE;")
lines.append("    DECLARE v_rf_rate DECIMAL(8,4) DEFAULT 4.50;  -- approximate risk-free rate (annualized %)")
lines.append("")
lines.append("    SELECT MAX(price_date) INTO v_end_date FROM stock_prices;")
lines.append("    SET v_start_date = DATE_SUB(v_end_date, INTERVAL 12 MONTH);")
lines.append("")
lines.append("    -- 12-month returns")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_rebal_returns;")
lines.append("    CREATE TEMPORARY TABLE tmp_rebal_returns AS")
lines.append("    SELECT")
lines.append("        e.ticker,")
lines.append("        ROUND((e.adj_close - s.adj_close) / s.adj_close * 100, 4) AS return_12m")
lines.append("    FROM (")
lines.append("        SELECT ticker, adj_close FROM stock_prices sp1")
lines.append("        WHERE price_date = (SELECT MAX(price_date) FROM stock_prices sp2 WHERE sp2.ticker = sp1.ticker AND sp2.price_date <= v_end_date)")
lines.append("    ) e")
lines.append("    JOIN (")
lines.append("        SELECT ticker, adj_close FROM stock_prices sp3")
lines.append("        WHERE price_date = (SELECT MIN(price_date) FROM stock_prices sp4 WHERE sp4.ticker = sp3.ticker AND sp4.price_date >= v_start_date)")
lines.append("    ) s ON e.ticker = s.ticker;")
lines.append("")
lines.append("    -- Daily returns for sigma calculation")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_rebal_daily;")
lines.append("    CREATE TEMPORARY TABLE tmp_rebal_daily AS")
lines.append("    SELECT")
lines.append("        sp.ticker,")
lines.append("        (sp.adj_close - prev.adj_close) / prev.adj_close * 100 AS daily_return")
lines.append("    FROM stock_prices sp")
lines.append("    INNER JOIN stock_prices prev")
lines.append("        ON sp.ticker = prev.ticker")
lines.append("        AND prev.price_date = (SELECT MAX(price_date) FROM stock_prices sp7 WHERE sp7.ticker = sp.ticker AND sp7.price_date < sp.price_date)")
lines.append("    WHERE sp.price_date >= v_start_date AND sp.price_date <= v_end_date;")
lines.append("")
lines.append("    -- Sigma per ticker")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_rebal_sigma;")
lines.append("    CREATE TEMPORARY TABLE tmp_rebal_sigma AS")
lines.append("    SELECT")
lines.append("        ticker,")
lines.append("        ROUND(STDDEV(daily_return) * SQRT(252), 4) AS ann_sigma")
lines.append("    FROM tmp_rebal_daily")
lines.append("    GROUP BY ticker;")
lines.append("")
lines.append("    -- Final output with recommendations")
lines.append("    SELECT")
lines.append("        r.ticker,")
lines.append("        pw.asset_class,")
lines.append("        pw.weight_pct AS current_allocation_pct,")
lines.append("        r.return_12m AS trailing_12m_return_pct,")
lines.append("        sig.ann_sigma AS annualized_sigma_pct,")
lines.append("        ROUND((r.return_12m - v_rf_rate) / sig.ann_sigma, 4) AS sharpe_ratio,")
lines.append("        CASE")
lines.append("            WHEN r.return_12m < -5 AND (r.return_12m - v_rf_rate) / sig.ann_sigma < 0")
lines.append("                THEN 'SELL'")
lines.append("            WHEN r.return_12m > 10 AND (r.return_12m - v_rf_rate) / sig.ann_sigma > 0.5")
lines.append("                THEN 'BUY'")
lines.append("            ELSE 'HOLD'")
lines.append("        END AS recommendation,")
lines.append("        CASE")
lines.append("            WHEN r.return_12m < -5 AND (r.return_12m - v_rf_rate) / sig.ann_sigma < 0")
lines.append("                THEN 'Negative return + negative risk-adjusted performance. Consider reducing position.'")
lines.append("            WHEN r.return_12m > 10 AND (r.return_12m - v_rf_rate) / sig.ann_sigma > 0.5")
lines.append("                THEN 'Strong return + favorable risk-adjusted performance. Consider increasing position.'")
lines.append("            ELSE 'Moderate performance. Maintain current allocation.'")
lines.append("        END AS rationale")
lines.append("    FROM tmp_rebal_returns r")
lines.append("    JOIN tmp_rebal_sigma sig ON r.ticker = sig.ticker")
lines.append("    JOIN portfolio_weights pw ON r.ticker = pw.ticker")
lines.append("    ORDER BY")
lines.append("        FIELD(CASE")
lines.append("            WHEN r.return_12m < -5 AND (r.return_12m - v_rf_rate) / sig.ann_sigma < 0 THEN 'SELL'")
lines.append("            WHEN r.return_12m > 10 AND (r.return_12m - v_rf_rate) / sig.ann_sigma > 0.5 THEN 'BUY'")
lines.append("            ELSE 'HOLD'")
lines.append("        END, 'BUY', 'HOLD', 'SELL');")
lines.append("")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_rebal_returns;")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_rebal_daily;")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_rebal_sigma;")
lines.append("END //")
lines.append("DELIMITER ;")
lines.append("")

# ---------- SP 5: POST-REBALANCING ANALYSIS ----------
lines.append("-- ------------------------------------------------------------")
lines.append("-- SP 5: sp_post_rebalancing_analysis")
lines.append("-- Compares current portfolio metrics against a proposed")
lines.append("-- rebalanced portfolio. The rebalancing logic:")
lines.append("--   - Overweight assets with BUY recommendation (+3% weight)")
lines.append("--   - Underweight assets with SELL recommendation (-3% weight)")
lines.append("--   - HOLD assets keep current weight, then normalize to 100%")
lines.append("-- Outputs side-by-side current vs. projected metrics.")
lines.append("-- ------------------------------------------------------------")
lines.append("DROP PROCEDURE IF EXISTS sp_post_rebalancing_analysis;")
lines.append("DELIMITER //")
lines.append("CREATE PROCEDURE sp_post_rebalancing_analysis()")
lines.append("BEGIN")
lines.append("    DECLARE v_end_date DATE;")
lines.append("    DECLARE v_start_date DATE;")
lines.append("    DECLARE v_rf_rate DECIMAL(8,4) DEFAULT 4.50;")
lines.append("    DECLARE v_total_new_weight DECIMAL(8,4);")
lines.append("")
lines.append("    SELECT MAX(price_date) INTO v_end_date FROM stock_prices;")
lines.append("    SET v_start_date = DATE_SUB(v_end_date, INTERVAL 12 MONTH);")
lines.append("")
lines.append("    -- 12-month returns")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_post_returns;")
lines.append("    CREATE TEMPORARY TABLE tmp_post_returns AS")
lines.append("    SELECT")
lines.append("        e.ticker,")
lines.append("        ROUND((e.adj_close - s.adj_close) / s.adj_close * 100, 4) AS return_12m")
lines.append("    FROM (")
lines.append("        SELECT ticker, adj_close FROM stock_prices sp1")
lines.append("        WHERE price_date = (SELECT MAX(price_date) FROM stock_prices sp2 WHERE sp2.ticker = sp1.ticker AND sp2.price_date <= v_end_date)")
lines.append("    ) e")
lines.append("    JOIN (")
lines.append("        SELECT ticker, adj_close FROM stock_prices sp3")
lines.append("        WHERE price_date = (SELECT MIN(price_date) FROM stock_prices sp4 WHERE sp4.ticker = sp3.ticker AND sp4.price_date >= v_start_date)")
lines.append("    ) s ON e.ticker = s.ticker;")
lines.append("")
lines.append("    -- Daily returns for sigma")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_post_daily;")
lines.append("    CREATE TEMPORARY TABLE tmp_post_daily AS")
lines.append("    SELECT")
lines.append("        sp.ticker,")
lines.append("        (sp.adj_close - prev.adj_close) / prev.adj_close * 100 AS daily_return")
lines.append("    FROM stock_prices sp")
lines.append("    INNER JOIN stock_prices prev")
lines.append("        ON sp.ticker = prev.ticker")
lines.append("        AND prev.price_date = (SELECT MAX(price_date) FROM stock_prices sp8 WHERE sp8.ticker = sp.ticker AND sp8.price_date < sp.price_date)")
lines.append("    WHERE sp.price_date >= v_start_date AND sp.price_date <= v_end_date;")
lines.append("")
lines.append("    -- Sigma per ticker")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_post_sigma;")
lines.append("    CREATE TEMPORARY TABLE tmp_post_sigma AS")
lines.append("    SELECT")
lines.append("        ticker,")
lines.append("        ROUND(STDDEV(daily_return) * SQRT(252), 4) AS ann_sigma")
lines.append("    FROM tmp_post_daily")
lines.append("    GROUP BY ticker;")
lines.append("")
lines.append("    -- Proposed new weights based on recommendations")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_new_weights;")
lines.append("    CREATE TEMPORARY TABLE tmp_new_weights AS")
lines.append("    SELECT")
lines.append("        pw.ticker,")
lines.append("        pw.weight_pct AS old_weight,")
lines.append("        CASE")
lines.append("            WHEN r.return_12m > 10 AND (r.return_12m - v_rf_rate) / sig.ann_sigma > 0.5")
lines.append("                THEN pw.weight_pct + 3.0")
lines.append("            WHEN r.return_12m < -5 AND (r.return_12m - v_rf_rate) / sig.ann_sigma < 0")
lines.append("                THEN GREATEST(pw.weight_pct - 3.0, 0)")
lines.append("            ELSE pw.weight_pct")
lines.append("        END AS raw_new_weight,")
lines.append("        r.return_12m,")
lines.append("        sig.ann_sigma")
lines.append("    FROM portfolio_weights pw")
lines.append("    JOIN tmp_post_returns r ON pw.ticker = r.ticker")
lines.append("    JOIN tmp_post_sigma sig ON pw.ticker = sig.ticker;")
lines.append("")
lines.append("    -- Normalize weights to sum to 100%")
lines.append("    SELECT SUM(raw_new_weight) INTO v_total_new_weight FROM tmp_new_weights;")
lines.append("")
lines.append("    -- Output: side-by-side comparison")
lines.append("    -- Result Set 1: Per-asset comparison")
lines.append("    SELECT")
lines.append("        nw.ticker,")
lines.append("        nw.old_weight AS current_weight_pct,")
lines.append("        ROUND(nw.raw_new_weight / v_total_new_weight * 100, 2) AS new_weight_pct,")
lines.append("        ROUND(nw.raw_new_weight / v_total_new_weight * 100 - nw.old_weight, 2) AS weight_change_pct,")
lines.append("        nw.return_12m AS trailing_return_pct,")
lines.append("        nw.ann_sigma AS ann_sigma_pct")
lines.append("    FROM tmp_new_weights nw")
lines.append("    ORDER BY nw.ticker;")
lines.append("")
lines.append("    -- Result Set 2: Portfolio-level metrics comparison")
lines.append("    SELECT 'Weighted Return (12M)' AS metric,")
lines.append("        ROUND(SUM(nw.return_12m * nw.old_weight / 100), 4) AS current_portfolio,")
lines.append("        ROUND(SUM(nw.return_12m * (nw.raw_new_weight / v_total_new_weight * 100) / 100), 4) AS projected_portfolio,")
lines.append("        ROUND(")
lines.append("            SUM(nw.return_12m * (nw.raw_new_weight / v_total_new_weight * 100) / 100)")
lines.append("            - SUM(nw.return_12m * nw.old_weight / 100)")
lines.append("        , 4) AS change")
lines.append("    FROM tmp_new_weights nw")
lines.append("    UNION ALL")
lines.append("    SELECT 'Weighted Sigma (Ann.)' AS metric,")
lines.append("        ROUND(SUM(nw.ann_sigma * nw.old_weight / 100), 4) AS current_portfolio,")
lines.append("        ROUND(SUM(nw.ann_sigma * (nw.raw_new_weight / v_total_new_weight * 100) / 100), 4) AS projected_portfolio,")
lines.append("        ROUND(")
lines.append("            SUM(nw.ann_sigma * (nw.raw_new_weight / v_total_new_weight * 100) / 100)")
lines.append("            - SUM(nw.ann_sigma * nw.old_weight / 100)")
lines.append("        , 4) AS change")
lines.append("    FROM tmp_new_weights nw")
lines.append("    UNION ALL")
lines.append("    SELECT 'Sharpe Ratio' AS metric,")
lines.append("        ROUND(")
lines.append("            (SUM(nw.return_12m * nw.old_weight / 100) - v_rf_rate)")
lines.append("            / SUM(nw.ann_sigma * nw.old_weight / 100)")
lines.append("        , 4) AS current_portfolio,")
lines.append("        ROUND(")
lines.append("            (SUM(nw.return_12m * (nw.raw_new_weight / v_total_new_weight * 100) / 100) - v_rf_rate)")
lines.append("            / SUM(nw.ann_sigma * (nw.raw_new_weight / v_total_new_weight * 100) / 100)")
lines.append("        , 4) AS projected_portfolio,")
lines.append("        ROUND(")
lines.append("            (SUM(nw.return_12m * (nw.raw_new_weight / v_total_new_weight * 100) / 100) - v_rf_rate)")
lines.append("            / SUM(nw.ann_sigma * (nw.raw_new_weight / v_total_new_weight * 100) / 100)")
lines.append("            - (SUM(nw.return_12m * nw.old_weight / 100) - v_rf_rate)")
lines.append("            / SUM(nw.ann_sigma * nw.old_weight / 100)")
lines.append("        , 4) AS change")
lines.append("    FROM tmp_new_weights nw;")
lines.append("")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_post_returns;")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_post_daily;")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_post_sigma;")
lines.append("    DROP TEMPORARY TABLE IF EXISTS tmp_new_weights;")
lines.append("END //")
lines.append("DELIMITER ;")
lines.append("")

# ============================================================
# SECTION 7: SAMPLE CALL STATEMENTS
# ============================================================
lines.append("-- ============================================================")
lines.append("-- STEP 7: SAMPLE CALL STATEMENTS")
lines.append("-- ============================================================")
lines.append("")
lines.append("-- SP 1: Portfolio Returns")
lines.append("CALL sp_portfolio_returns(12);   -- 12-month returns")
lines.append("CALL sp_portfolio_returns(18);   -- 18-month returns")
lines.append("CALL sp_portfolio_returns(24);   -- 24-month returns")
lines.append("")
lines.append("-- SP 2: Asset Correlations")
lines.append("CALL sp_asset_correlations();    -- full correlation matrix + variance table")
lines.append("")
lines.append("-- SP 3: Portfolio Sigma")
lines.append("CALL sp_portfolio_sigma(12);     -- 12-month sigma")
lines.append("CALL sp_portfolio_sigma(18);     -- 18-month sigma")
lines.append("CALL sp_portfolio_sigma(24);     -- 24-month sigma")
lines.append("")
lines.append("-- SP 4: Rebalancing Recommendations")
lines.append("CALL sp_rebalancing_recommendations();")
lines.append("")
lines.append("-- SP 5: Post-Rebalancing Analysis")
lines.append("CALL sp_post_rebalancing_analysis();")
lines.append("")
lines.append("-- ============================================================")
lines.append("-- END OF SCRIPT")
lines.append("-- ============================================================")

# Write the file
output_path = r'C:\Users\betan\OneDrive\Desktop\Claude - JFB\Code\portfolio_analysis_complete.sql'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

total_inserts = sum(len(all_data[t]) for t in tickers)
print(f"\nSQL file written to: {output_path}")
print(f"Total data rows: {total_inserts}")
print(f"File size: {len(chr(10).join(lines)):,} characters")
